name: Publish Python Package to PyPi
on:
  release:
    types: [published]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install PDM and Python
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
      - name: Install dependencies
        run: pdm install
      - name: Run Tests
        run: pdm run pytest
  publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: pdm-project/setup-pdm@v4
      - name: Publish package distributions to PyPI
        run: pdm publish
